#pragma once

#define PIN_LNB_POWER 19
#define PIN_LNB_TONE 20

#define MOTOR_ALT_PWM 22
#define MOTOR_ALT_FORWARD 24
#define MOTOR_ALT_REVERSE 25
#define MOTOR_ALT_QUAD_A 16
#define MOTOR_ALT_QUAD_B 17

#define MOTOR_AZ_PWM 21
#define MOTOR_AZ_FORWARD 26
#define MOTOR_AZ_REVERSE 27
#define MOTOR_AZ_QUAD_A 14
#define MOTOR_AZ_QUAD_B 15